-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ImageMeta" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "imageId" INTEGER NOT NULL,
    "sourceType" TEXT NOT NULL DEFAULT 'unknown',
    "prompt" TEXT,
    "negativePrompt" TEXT,
    "model" TEXT,
    "modelHash" TEXT,
    "baseSampler" TEXT,
    "baseScheduler" TEXT,
    "baseSteps" INTEGER,
    "baseCfgScale" REAL,
    "baseSeed" TEXT,
    "upscaleSampler" TEXT,
    "upscaleScheduler" TEXT,
    "upscaleSteps" INTEGER,
    "upscaleCfgScale" REAL,
    "upscaleSeed" TEXT,
    "upscaleFactor" REAL,
    "upscaler" TEXT,
    "sizeWidth" INTEGER,
    "sizeHeight" INTEGER,
    "clipSkip" INTEGER,
    "vae" TEXT,
    "denoiseStrength" REAL,
    "parseWarningsJson" TEXT NOT NULL DEFAULT '[]',
    "parseVersion" TEXT NOT NULL DEFAULT '',
    "rawJson" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ImageMeta_imageId_fkey" FOREIGN KEY ("imageId") REFERENCES "Image" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_ImageMeta" (
    "id",
    "imageId",
    "sourceType",
    "prompt",
    "negativePrompt",
    "model",
    "modelHash",
    "baseSampler",
    "baseScheduler",
    "baseSteps",
    "baseCfgScale",
    "baseSeed",
    "upscaleSampler",
    "upscaleScheduler",
    "upscaleSteps",
    "upscaleCfgScale",
    "upscaleSeed",
    "upscaleFactor",
    "upscaler",
    "sizeWidth",
    "sizeHeight",
    "clipSkip",
    "vae",
    "denoiseStrength",
    "parseWarningsJson",
    "parseVersion",
    "rawJson",
    "createdAt",
    "updatedAt"
)
SELECT
    "id",
    "imageId",
    "sourceType",
    "prompt",
    "negativePrompt",
    "model",
    "modelHash",
    "baseSampler",
    "baseScheduler",
    "baseSteps",
    "baseCfgScale",
    "baseSeed",
    "upscaleSampler",
    "upscaleScheduler",
    "upscaleSteps",
    "upscaleCfgScale",
    "upscaleSeed",
    "upscaleFactor",
    "upscaler",
    "sizeWidth",
    "sizeHeight",
    "clipSkip",
    "vae",
    "denoiseStrength",
    "parseWarningsJson",
    "parseVersion",
    "rawJson",
    "createdAt",
    "updatedAt"
FROM "ImageMeta";
DROP TABLE "ImageMeta";
ALTER TABLE "new_ImageMeta" RENAME TO "ImageMeta";
CREATE UNIQUE INDEX "ImageMeta_imageId_key" ON "ImageMeta"("imageId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
